var n="function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){a!=Array.prototype&&a!=Object.prototype&&(a[c]=b.value)};function t(a){a=["object"==typeof globalThis&&globalThis,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var c=0;c<a.length;++c){var b=a[c];if(b&&b.Math==Math)return b}throw Error("Cannot find global object");}var aa=t(this);
function ba(a,c){if(c){var b=aa;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in b||(b[e]={});b=b[e]}a=a[a.length-1];d=b[a];c=c(d);c!=d&&null!=c&&n(b,a,{configurable:!0,writable:!0,value:c})}}
ba("String.prototype.startsWith",function(a){return a?a:function(c,b){if(null==this)throw new TypeError("The 'this' value for String.prototype.startsWith must not be null or undefined");if(c instanceof RegExp)throw new TypeError("First argument to String.prototype.startsWith must not be a regular expression");var d=this.length,e=c.length;b=Math.max(0,Math.min(b|0,this.length));for(var f=0;f<e&&b<d;)if(this[b++]!=c[f++])return!1;return f>=e}});var ca=[];
function v(a,c,b){b=void 0===b?"":b;a="["+(new Date).toISOString().split("T")[1].substring(0,8)+"] ["+a+"] "+c+" "+(b?"\nDetail: "+b:"");ca.push(a);console.log(a)}v("SYSTEM","Application initialized successfully.");window.addEventListener("error",function(a){var c=a.error?a.error.stack:"No call stack available.";v("CRITICAL_ERROR",a.message,c);w("Uncaught Runtime Exception",a.message,c)});
function w(a,c,b){document.getElementById("popup-err-type").textContent=a;document.getElementById("popup-err-message").textContent=c;document.getElementById("popup-err-stack").textContent=b||"No call stack trace records.";a=document.getElementById("btn-toggle-log");document.getElementById("popup-err-stack").style.display="none";a.textContent="ดู log ตัวเต็ม (Show Full Log) ▼";document.getElementById("notification-popup-overlay").style.display="flex"}
var z=document.getElementById("file"),da=document.getElementById("palette-file-reader"),A=document.getElementById("run"),B=document.getElementById("copy"),C=document.getElementById("download"),D=document.getElementById("status"),E=document.getElementById("output"),F=document.querySelector(".image-preview-container"),G=document.querySelector("canvas"),H=G.getContext("2d",{h:!0}),L=document.getElementById("width"),M=document.getElementById("height"),ea=document.getElementById("factor"),N=document.getElementById("ratio"),
O=0,T=0,U="image/png",V="pic2mkca.png",W=".png",X=[];document.querySelectorAll(".color-pair").forEach(function(a,c){var b=a.querySelector('input[type="color"]'),d=a.querySelector(".colortext");b.addEventListener("input",function(){d.value=this.value});d.addEventListener("change",function(){var e=this.value.trim();e.startsWith("#")||(e="#"+e);/^#[0-9A-Fa-f]{6}$/.test(e)&&(this.value=b.value=e,v("PALETTE","Color slot "+(c+1)+" updated to "+e))})});
da.addEventListener("change",function(a){var c=a.target.files[0];c&&(a=new FileReader,a.onload=function(b){var d=[];b.target.result.split(/\r?\n/).forEach(function(g){(g=g.trim().replace(/;.*$/,"").trim())&&(g=g.match(/#?([0-9A-Fa-f]{6})/))&&d.push("#"+g[1].toLowerCase())});if(0<d.length){b=document.querySelectorAll(".color-pair");for(var e=0;e<b.length&&e<d.length;e++){var f=b[e].querySelector(".colortext");b[e].querySelector('input[type="color"]').value=d[e];f.value=d[e]}D.textContent="System: Loaded "+
Math.min(b.length,d.length)+" colors from palette file.";v("PALETTE","Imported external palette from "+c.name+". Total found: "+d.length)}else alert("No valid hex colors found in the selected file.")},a.readAsText(c))});function fa(){X=[];document.querySelectorAll(".color-pair").forEach(function(a){a=a.querySelector('input[type="color"]').value;X.push({r:parseInt(a.substring(1,3),16),g:parseInt(a.substring(3,5),16),f:parseInt(a.substring(5,7),16)})})}
function Y(a,c,b){for(var d=Infinity,e=1,f=0;f<X.length;f++){var g=Math.pow(a-X[f].r,2)+Math.pow(c-X[f].g,2)+Math.pow(b-X[f].f,2);g<d&&(d=g,e=f+1)}return e}
z.addEventListener("change",function(){E.value="";var a=z.files[0];if(a){U=a.type||"image/png";var c=a.name.lastIndexOf(".");-1!==c?W=a.name.substring(c):W=".png";".gif"===W.toLowerCase()&&(W=".png");c=new FileReader;c.onload=function(b){var d=new Image;d.onload=function(){try{F&&(F.style.display="flex");O=d.naturalWidth;T=d.naturalHeight;document.getElementById("original-res").textContent="Size: "+d.naturalWidth+" x "+d.naturalHeight+" px";document.getElementById("canvas-res").textContent="Size: -- x -- px";
var e=document.getElementById("original-preview-zone");e.innerHTML="";e.appendChild(d);document.querySelectorAll("input[disabled]").forEach(function(f){return f.removeAttribute("disabled")});A.removeAttribute("disabled");C.removeAttribute("disabled");Z();D.textContent="Ready: "+a.name+" Loaded Successfully.";v("IMAGE","Loaded target resource file: "+a.name+" ("+d.naturalWidth+"x"+d.naturalHeight+")")}catch(f){w("Image Allocation Core Exception",f.message,f.stack)}};d.src=b.target.result};c.readAsDataURL(a)}});
function Z(){if(document.querySelector("#original-preview-zone img"))if(document.getElementById("full-width").checked)L.value=160,M.value=Math.round(160/O*T);else if(document.getElementById("full-height").checked)M.value=120,L.value=Math.round(120/T*O);else if(document.getElementById("scale").checked){var a=parseFloat(ea.value)||.1;L.value=Math.round(O*a);M.value=Math.round(T*a)}}
document.querySelectorAll('input[name="resize"], #factor').forEach(function(a){a.addEventListener("change",Z);a.addEventListener("input",Z)});L.addEventListener("input",function(){N.checked&&0<O&&(M.value=Math.round(T*(parseInt(this.value)||1)/O))});M.addEventListener("input",function(){N.checked&&0<T&&(L.value=Math.round(O*(parseInt(this.value)||1)/T))});
A.addEventListener("click",function(a){a.preventDefault();try{var c=document.querySelector("#original-preview-zone img");if(c){V="pic2mkca."+(new Date).toISOString().replace(/:/g,"-").replace(/\.\d{3}/,"")+W;fa();var b=parseInt(L.value)||16,d=parseInt(M.value)||16;G.width=b;G.height=d;document.getElementById("canvas-res").textContent="Size: "+b+" x "+d+" px";var e=document.querySelector('input[name="mode"]:checked').id.replace("mode-","");D.textContent="Processing matrix pipeline ["+e+"]...";v("PIPELINE",
"Start processing conversion. Target filename: "+V+". Mode: "+e);H.clearRect(0,0,b,d);H.drawImage(c,0,0,b,d);var f=H.getImageData(0,0,b,d).data;a=[];for(c=0;c<d;c++)a[c]=Array(b);if("solid"===e)for(var g=0;g<d;g++)for(var k=0;k<b;k++){var h=4*(g*b+k);a[g][k]=128>f[h+3]?"0":Y(f[h],f[h+1],f[h+2]).toString(16)}else if("error"===e)for(var r=new Float32Array(b*d*3),l=0;l<d;l++){c={};for(var q=0;q<b;c={c:c.c,b:c.b,a:c.a},q++){var I=4*(l*b+q),P=3*(l*b+q);if(128>f[I+3])a[l][q]="0";else{g=f[I]+r[P];k=f[I+
1]+r[P+1];h=f[I+2]+r[P+2];g=Math.max(0,Math.min(255,g));k=Math.max(0,Math.min(255,k));h=Math.max(0,Math.min(255,h));var x=Y(g,k,h);a[l][q]=x.toString(16);var Q=X[x-1];c.c=g-Q.r;c.b=k-Q.g;c.a=h-Q.f;var K=function(u){return function(p,J,R){0<=p&&p<b&&0<=J&&J<d&&128<=f[4*(J*b+p)+3]&&(p=3*(J*b+p),r[p]+=u.c*R,r[p+1]+=u.b*R,r[p+2]+=u.a*R)}}(c);K(q+1,l,.4375);K(q-1,l+1,.1875);K(q,l+1,.3125);K(q+1,l+1,.0625)}}}else if("bayer"===e)for(g=[[0,8,2,10],[12,4,14,6],[3,11,1,9],[15,7,13,5]],k=0;k<d;k++)for(h=0;h<
b;h++)x=4*(k*b+h),128>f[x+3]?a[k][h]="0":(l=g[k%4][h%4]/16-.5,a[k][h]=Y(f[x]+48*l,f[x+1]+48*l,f[x+2]+48*l).toString(16));H.clearRect(0,0,b,d);var m=H.createImageData(b,d);for(g=0;g<d;g++)for(k=0;k<b;k++){var y=a[g][k];h=4*(g*b+k);if(y&&"0"!==y){var S=X[parseInt(y,16)-1];m.data[h]=S.r;m.data[h+1]=S.g;m.data[h+2]=S.f;m.data[h+3]=255}else m.data[h]=0,m.data[h+1]=0,m.data[h+2]=0,m.data[h+3]=0}H.putImageData(m,0,0);m="img`\n";for(y=0;y<d;y++)m+="    "+a[y].join("")+"\n";E.value=m+"`";B.removeAttribute("disabled");
D.textContent="Success: Convert completed in ["+e.toUpperCase()+"] mode.";v("PIPELINE","Render successful. Filename updated to "+V)}}catch(u){v("MATRIX_FAULT",u.message,u.stack),w("Matrix Pipeline Conversion Fault",u.message,u.stack)}});B.addEventListener("click",function(a){a.preventDefault();E.select();document.execCommand("copy");B.innerText="Code copied to clipboard!";v("IO","Output vector text data copied into clipboard register.");setTimeout(function(){B.innerText="Copy code"},2E3)});
C.addEventListener("click",function(a){a.preventDefault();try{if(!document.querySelector("#original-preview-zone img"))return alert("No active image asset to download.");a=U;"image/gif"===U&&(a="image/png");var c=G.toDataURL(a),b=document.createElement("a");b.href=c;b.download=V;b.click();b.remove();v("IO","Triggered canvas attachment file download: "+V)}catch(d){v("DOWNLOAD_FAULT",d.message,d.stack),w("IO Canvas Download Error",d.message,d.stack)}});
