function n(a,c,b){if(null==a)throw new TypeError("The 'this' value for String.prototype."+b+" must not be null or undefined");if(c instanceof RegExp)throw new TypeError("First argument to String.prototype."+b+" must not be a regular expression");return a+""}var aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){a!=Array.prototype&&a!=Object.prototype&&(a[c]=b.value)};
function ba(a){a=["object"==typeof globalThis&&globalThis,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var c=0;c<a.length;++c){var b=a[c];if(b&&b.Math==Math)return b}throw Error("Cannot find global object");}var ca=ba(this);function t(a,c){if(c){var b=ca;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in b||(b[e]={});b=b[e]}a=a[a.length-1];d=b[a];c=c(d);c!=d&&null!=c&&aa(b,a,{configurable:!0,writable:!0,value:c})}}
t("String.prototype.repeat",function(a){return a?a:function(c){var b=n(this,null,"repeat");if(0>c||1342177279<c)throw new RangeError("Invalid count value");c|=0;for(var d="";c;)if(c&1&&(d+=b),c>>>=1)b+=b;return d}});t("String.prototype.padStart",function(a){return a?a:function(c,b){var d=n(this,null,"padStart");c-=d.length;b=void 0!==b?String(b):" ";return(0<c&&b?b.repeat(Math.ceil(c/b.length)).substring(0,c):"")+d}});
t("String.prototype.startsWith",function(a){return a?a:function(c,b){var d=n(this,c,"startsWith");c+="";var e=d.length,f=c.length;b=Math.max(0,Math.min(b|0,d.length));for(var g=0;g<f&&b<e;)if(d[b++]!=c[g++])return!1;return g>=f}});t("String.prototype.endsWith",function(a){return a?a:function(c,b){var d=n(this,c,"endsWith");c+="";void 0===b&&(b=d.length);b=Math.max(0,Math.min(b|0,d.length));for(var e=c.length;0<e&&0<b;)if(d[--b]!=c[--e])return!1;return 0>=e}});var da=[];
function v(a,c,b){b=void 0===b?"":b;a="["+(new Date).toISOString().split("T")[1].substring(0,8)+"] ["+a+"] "+c+" "+(b?"\nDetail: "+b:"");da.push(a);console.log(a)}v("SYSTEM","Application initialized successfully.");window.addEventListener("error",function(a){var c=a.error?a.error.stack:"No call stack available.";v("CRITICAL_ERROR",a.message,c);w("Uncaught Runtime Exception",a.message,c)});
function w(a,c,b){document.getElementById("popup-err-type").textContent=a;document.getElementById("popup-err-message").textContent=c;document.getElementById("popup-err-stack").textContent=b||"No call stack trace records.";a=document.getElementById("btn-toggle-log");document.getElementById("popup-err-stack").style.display="none";a.textContent="ดู log ตัวเต็ม (Show Full Log) ▼";document.getElementById("notification-popup-overlay").style.display="flex"}
var z=document.getElementById("file"),ea=document.getElementById("palette-file-reader"),A=document.getElementById("run"),B=document.getElementById("copy"),C=document.getElementById("download"),D=document.getElementById("status"),E=document.getElementById("output"),F=document.querySelector(".image-preview-container"),G=document.querySelector("canvas"),H=G.getContext("2d",{h:!0}),I=document.getElementById("width"),M=document.getElementById("height"),fa=document.getElementById("factor"),ha=document.getElementById("ratio"),
N=0,O=0,P="image/png",Q="sprite",R="",W=".png",X=[];function ia(){var a=new Date;return"_"+a.getFullYear()+String(a.getMonth()+1).padStart(2,"0")+String(a.getDate()).padStart(2,"0")+"_"+String(a.getHours()).padStart(2,"0")+String(a.getMinutes()).padStart(2,"0")+String(a.getSeconds()).padStart(2,"0")}
document.querySelectorAll(".color-pair").forEach(function(a,c){var b=a.querySelector('input[type="color"]'),d=a.querySelector(".colortext");b.addEventListener("input",function(){d.value=this.value});d.addEventListener("change",function(){var e=this.value.trim();e.startsWith("#")||(e="#"+e);/^#[0-9A-Fa-f]{6}$/.test(e)&&(this.value=b.value=e,v("PALETTE","Color slot "+(c+1)+" updated to "+e))})});
ea.addEventListener("change",function(a){var c=a.target.files[0];c&&(a=new FileReader,a.onload=function(b){var d=[];b.target.result.split(/\r?\n/).forEach(function(g){(g=g.trim().replace(/;.*$/,"").trim())&&(g=g.match(/#?([0-9A-Fa-f]{6})/))&&d.push("#"+g[1].toLowerCase())});if(0<d.length){b=document.querySelectorAll(".color-pair");for(var e=0;e<b.length&&e<d.length;e++){var f=b[e].querySelector(".colortext");b[e].querySelector('input[type="color"]').value=d[e];f.value=d[e]}D.textContent="System: Loaded "+
Math.min(b.length,d.length)+" colors from palette file.";v("PALETTE","Imported external palette from "+c.name+". Total found: "+d.length)}else alert("No valid hex colors found in the selected file.")},a.readAsText(c))});function ja(){X=[];document.querySelectorAll(".color-pair").forEach(function(a){a=a.querySelector('input[type="color"]').value;X.push({r:parseInt(a.substring(1,3),16),g:parseInt(a.substring(3,5),16),f:parseInt(a.substring(5,7),16)})})}
function Y(a,c,b){for(var d=Infinity,e=1,f=0;f<X.length;f++){var g=Math.pow(a-X[f].r,2)+Math.pow(c-X[f].g,2)+Math.pow(b-X[f].f,2);g<d&&(d=g,e=f+1)}return e}
z.addEventListener("change",function(){E.value="";var a=z.files[0];if(a){P=a.type||"image/png";var c=a.name.lastIndexOf(".");-1!==c?(Q=a.name.substring(0,c)+"_converted",W=a.name.substring(c)):(Q=a.name+"_converted",W=".png");a.name.toLowerCase().endsWith(".gif")&&(W=".png");c=new FileReader;c.onload=function(b){var d=new Image;d.onload=function(){try{F&&(F.style.display="flex");N=d.naturalWidth;O=d.naturalHeight;document.getElementById("original-res").textContent="Size: "+d.naturalWidth+" x "+d.naturalHeight+
" px";document.getElementById("canvas-res").textContent="Size: -- x -- px";var e=document.getElementById("original-preview-zone");e.innerHTML="";e.appendChild(d);document.querySelectorAll("input[disabled]").forEach(function(f){return f.removeAttribute("disabled")});A.removeAttribute("disabled");C.removeAttribute("disabled");Z();D.textContent="Ready: "+a.name+" Loaded Successfully.";v("IMAGE","Loaded target resource file: "+a.name+" ("+d.naturalWidth+"x"+d.naturalHeight+")")}catch(f){w("Image Allocation Core Exception",
f.message,f.stack)}};d.src=b.target.result};c.readAsDataURL(a)}});function Z(){if(document.querySelector("#original-preview-zone img"))if(document.getElementById("full-width").checked)I.value=160,M.value=Math.round(160/N*O);else if(document.getElementById("full-height").checked)M.value=120,I.value=Math.round(120/O*N);else if(document.getElementById("scale").checked){var a=parseFloat(fa.value)||.1;I.value=Math.round(N*a);M.value=Math.round(O*a)}}
document.querySelectorAll('input[name="resize"], #factor').forEach(function(a){a.addEventListener("change",Z);a.addEventListener("input",Z)});I.addEventListener("input",function(){ha.checked&&0<N&&(M.value=Math.round(O*(parseInt(this.value)||1)/N))});M.addEventListener("input",function(){ha.checked&&0<O&&(I.value=Math.round(N*(parseInt(this.value)||1)/O))});
A.addEventListener("click",function(a){a.preventDefault();try{var c=document.querySelector("#original-preview-zone img");if(c){R=ia();ja();var b=parseInt(I.value)||16,d=parseInt(M.value)||16;G.width=b;G.height=d;document.getElementById("canvas-res").textContent="Size: "+b+" x "+d+" px";var e=document.querySelector('input[name="mode"]:checked').id.replace("mode-","");D.textContent="Processing matrix pipeline ["+e+"]...";v("PIPELINE","Start processing conversion. Target dimensions: "+b+"x"+d+". Mode: "+
e+". Assigned timestamp: "+R);H.clearRect(0,0,b,d);H.drawImage(c,0,0,b,d);var f=H.getImageData(0,0,b,d).data;a=[];for(c=0;c<d;c++)a[c]=Array(b);if("solid"===e)for(var g=0;g<d;g++)for(var k=0;k<b;k++){var h=4*(g*b+k);a[g][k]=128>f[h+3]?"0":Y(f[h],f[h+1],f[h+2]).toString(16)}else if("error"===e)for(var r=new Float32Array(b*d*3),l=0;l<d;l++){c={};for(var q=0;q<b;c={c:c.c,b:c.b,a:c.a},q++){var J=4*(l*b+q),S=3*(l*b+q);if(128>f[J+3])a[l][q]="0";else{g=f[J]+r[S];k=f[J+1]+r[S+1];h=f[J+2]+r[S+2];g=Math.max(0,
Math.min(255,g));k=Math.max(0,Math.min(255,k));h=Math.max(0,Math.min(255,h));var x=Y(g,k,h);a[l][q]=x.toString(16);var T=X[x-1];c.c=g-T.r;c.b=k-T.g;c.a=h-T.f;var L=function(u){return function(p,K,U){0<=p&&p<b&&0<=K&&K<d&&128<=f[4*(K*b+p)+3]&&(p=3*(K*b+p),r[p]+=u.c*U,r[p+1]+=u.b*U,r[p+2]+=u.a*U)}}(c);L(q+1,l,.4375);L(q-1,l+1,.1875);L(q,l+1,.3125);L(q+1,l+1,.0625)}}}else if("bayer"===e)for(g=[[0,8,2,10],[12,4,14,6],[3,11,1,9],[15,7,13,5]],k=0;k<d;k++)for(h=0;h<b;h++)x=4*(k*b+h),128>f[x+3]?a[k][h]="0":
(l=g[k%4][h%4]/16-.5,a[k][h]=Y(f[x]+48*l,f[x+1]+48*l,f[x+2]+48*l).toString(16));H.clearRect(0,0,b,d);var m=H.createImageData(b,d);for(g=0;g<d;g++)for(k=0;k<b;k++){var y=a[g][k];h=4*(g*b+k);if(y&&"0"!==y){var V=X[parseInt(y,16)-1];m.data[h]=V.r;m.data[h+1]=V.g;m.data[h+2]=V.f;m.data[h+3]=255}else m.data[h]=0,m.data[h+1]=0,m.data[h+2]=0,m.data[h+3]=0}H.putImageData(m,0,0);m="img`\n";for(y=0;y<d;y++)m+="    "+a[y].join("")+"\n";E.value=m+"`";B.removeAttribute("disabled");D.textContent="Success: Convert completed in ["+
e.toUpperCase()+"] mode.";v("PIPELINE","Render successful for ["+e.toUpperCase()+"] method.")}}catch(u){v("MATRIX_FAULT",u.message,u.stack),w("Matrix Pipeline Conversion Fault",u.message,u.stack)}});B.addEventListener("click",function(a){a.preventDefault();E.select();document.execCommand("copy");B.innerText="Code copied to clipboard!";v("IO","Output vector text data copied into clipboard register.");setTimeout(function(){B.innerText="Copy code"},2E3)});
C.addEventListener("click",function(a){a.preventDefault();try{if(!document.querySelector("#original-preview-zone img"))return alert("No active image asset to download.");a=P;"image/gif"===P&&(a="image/png");var c=""+Q+R+W,b=G.toDataURL(a),d=document.createElement("a");d.href=b;d.download=c;d.click();d.remove();v("IO","Triggered canvas attachment file download: "+c)}catch(e){v("DOWNLOAD_FAULT",e.message,e.stack),w("IO Canvas Download Error",e.message,e.stack)}});
